### ISSUE TITLE
Not compatible with galaxy S10?

### ISSUE THREAD

**Issue by zhouqin1983** [starryalley/Messages.png_Android#4]
Cannot install directly in Google play store (
Google says it is not compatible). Need to download APK and install manually. The program runs, and shows Garmin watch is connected. However, on the Garmin watch, it says phone app unreachable.

**Comment by starryalley** [comment]
I'm sorry but this is not maintained anymore. The incompatible thing is maybe due to some changes to google play so I will have to re-submit something to make this app available.

When the "phone app unreachable" happens it is either the firewall setting in your phone blocking it or preventing it from running in the background 24/7, or your are running recent Garmin Connect that removed a API that the app uses to connect to localhost.

Anyway I am still using it everyday on my Fenix 6 pro watch with Samsung S21. I have S8 and tested it was woring too but it was a few years ago.
I am running Garmin Connect 4.39 though.

**Comment by zhouqin1983** [comment]
Thanks for the reply! If you still use the program everyday, why not maintain it? Would be very useful! 
I did use Garmin Connect 4.39 as you specified. Also, the widget worked for a few hours yesterday, and then shows "phone app unreachable" again... I feel that, since the phone app always shows "Garmin connected" and can also correctly access phone notifications, maybe the problem is the nanohttp service?

**Comment by starryalley** [comment]
I stopped maintaining all my Garmin apps because the development environment in ConnectIQ is terrible. They didn't fix bugs and kept on creating new ones. It was 2-3 years ago. I don't know if things have improved? Anyway that's another story.

You may be correct that the nanohttp service may have stopped. What is the "Service Running" status in the app? 

If the Android app worked for a few hours on your environment and then stopped, could it be that the app's service stops running in the background due to other issue? For example maybe there is some system app that cleans up the device every few hours and stopped the background service from running. The Unquestionify app showing "CONNECTED" is just a status from ConnectIQ.

**Comment by zhouqin1983** [comment]
I see. I did not know Garmin environment is so terrible. I guess they don't care since they already got a portion of the market without a good development environment, and creating a good development environment will only help them to take Apple watch or Samsung watch's market share, which is almost impossible. Anyway, I checked "Service Running" is "Running", and somehow the widget worked fine at this moment... So weird... 
Another abnormal behavior is that, after receiving a message, my watch always asks "Launch Unquestionify?" even I have chosen "Always" everytime it asks. Then the watch says "Unquestionify 1 message", and then after I click, it shows "Loading message", and after a few seconds, I can finally see the message. Is this how the widget supposed to work?

**Comment by starryalley** [comment]
The "Launch Unquestionify" dialog appears even if user selects "Always". It is one of the issue I reported to Garmin but they never replied or fixed it. It is still like this 3 years afterwards. This dialog started to appear after a fimware update and they never documented this change. 

Yes I agree with what you said. They simply don't care because their watches will still sell regardlessly. That's why I abandoned this platform and ceased to be a ConnectIQ developer.

**Comment by zhouqin1983** [comment]
Thanks. OK... I think I will just return my Garmin in the hope that they will notice and make some change...

**Comment by starryalley** [comment]
I assume Fenix 7 and later should have multi-lanaguage support built-in. If that's the case there should be fewer people needing this app now.

Not sure about other lines of products. My partner's vicoactive 4s originally didn't have multi-lanaguage support but finally got it with a firmware update. But my Fenix 6 pro never got it.

**Comment by zhouqin1983** [comment]
Thanks for the info. Happy Labor's day!

**Comment by starryalley** [comment]
Thank you. It isn't our labour's day down here (Australia) though. But I do enjoy some of the labor's day sales from some US sites :P

Have a good day!! Hope you got it all sorted out with another (Garmin or not) watch. It's already 2023 yet i am still strugging with a supposedly highest end watch to read non-English text messages using my own custom app, that no longer works because they [changed something randomly](https://forums.garmin.com/developer/connect-iq/i/bug-reports/connect-mobile-4-40-makeimagerequest-localhost-error?CommentSortBy=CreatedDate&CommentSortOrder=Descending).

**Comment by zhouqin1983** [comment]
Thank you for kindly helping me even the program is not maintained! I did not realize you live in Australia. Wish I could visit there one day. Best wishes~~
